import Head from "next/head";
import Image from "next/image";

const Projects = ({projectsData}) => {
    console.log(projectsData);
    return (
        <div>
            <Head>
                <title>Projects - Nahid Hossain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/boy.png" />
            </Head>
            <div>
                {
                    projectsData.map((project) => (
                        <div key={project._id}>
                            <Image loader={() => project.img} src={project.img} alt="project image" height={200} width={200} />
                        </div>
                    ))
                }
            </div>
        </div>
    );
};

export default Projects;

export async function getStaticProps() {
    const projectsRes = await fetch('https://ndhossain.github.io/database/projects.json');
    const projectsData = await projectsRes.json();
    return {
      props: {
        projectsData,
      },
    }
}