import Head from "next/head";
import Image from "next/image";

const Projects = ({projectsData}) => {
    const openInNewTab = (url) => {
        const newWindow = window.open(url, '_blank', 'noopener,noreferrer')
        if (newWindow) newWindow.opener = null
    }

    const {result, success} = projectsData;

    return (
        <div>
            <Head>
                <title>Projects - Nahid Hossain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/boy.png" />
            </Head>
            <div className="mt-10">
                <h1 className="text-2xl font-bold text-center">My Projects</h1>
                <div className="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 justify-between mt-5 gap-2">
                    {
                        result?.map((project) => (
                            <div key={project._id} className="basis-1/3 dark:bg-white/10 bg-gray-900/10 border-1 border-white p-2 rounded-lg">
                                <div className="h-[200px] overflow-hidden justify-between p-1">
                                    <Image loader={() => project.img} src={project.img} alt="project image" height={200} width={600} />
                                </div>
                                <div className="flex flex-col justify-between mt-3 h-[150px]">
                                    <h1 className="text-xl font-bold">{project.projectName}</h1>
                                    <div className="mt-2 flex justify-between">
                                        <button className="px-3 py-1 border border-sky-600 text-sky-600 font-bold" onClick={() => openInNewTab(project.url)}>View Demo</button>
                                        <button className="px-3 py-1 border border-sky-600 text-sky-600 font-bold" onClick={() => openInNewTab(project.url)}>Details</button>
                                    </div>
                                </div>
                            </div>
                        ))
                    }
                </div>
                <div className="mt-10">
                    <h1 className="text-2xl font-bold text-center">Upcoming Projects</h1>
                    <p className="mt-5">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, maxime obcaecati voluptatum dolorum quaerat cum quam expedita libero esse neque perferendis et modi molestias repellat vitae necessitatibus ad doloremque officia. Odit magni dignissimos iusto quod impedit accusantium ducimus soluta error, obcaecati unde labore perferendis amet cum ex, earum mollitia culpa magnam quidem. Impedit dignissimos inventore in odio voluptatibus aspernatur distinctio velit mollitia iusto libero illo repellat at a nostrum quis, est molestias doloribus expedita numquam magnam consequatur ipsum hic! Molestiae iure possimus voluptatem quaerat distinctio aliquam, voluptatum obcaecati impedit consectetur delectus consequuntur error labore at, eos minus provident qui laudantium sed modi praesentium officia odit. Fugiat, atque? Illum vel sit, cum mollitia eligendi cumque atque id nesciunt, officiis ullam aliquam minus adipisci sapiente quo unde. Velit odio, quo, sint architecto sapiente necessitatibus similique harum, dignissimos deserunt porro quas aperiam mollitia voluptatum magnam est! Impedit nam accusantium fugiat dolorum ipsum a nihil velit libero at perferendis amet tempore, iure blanditiis omnis, veniam earum consectetur eaque quis aliquam. Ullam, in eaque! Alias, commodi tempore! Accusantium corporis officia eveniet odit quos nobis? Iste aspernatur cumque rerum maxime nemo laudantium, placeat voluptates distinctio voluptatum sed in! Voluptas culpa quidem quod voluptatum sequi obcaecati molestias!
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere dolor ex voluptatem quod, expedita asperiores, vero nobis nesciunt explicabo in consequatur labore perspiciatis inventore ad accusantium incidunt, consequuntur impedit quidem.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Projects;

export async function getStaticProps() {
    let dev = process.env.NODE_ENV !== 'production';
    let { DEV_URL, PROD_URL } = process.env;
    try {
        const projectsRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/projects`);
        const projectsData = await projectsRes.json();
        return {
            props: {
                projectsData,
            },
        }
    } catch (error) {
        console.log(error);
        return error
    }
}