import Head from "next/head";
import Bio from "../../components/homeComps/bio";

const About = ({educationData, experienceData}) => {
    return (
        <div className="my-10">
            <Head>
                <title>About - Nahid Hossain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/boy.png" />
            </Head>
            <Bio 
                educations={educationData} 
                experiences={experienceData} 
            />
        </div>
    );
};

export default About;

export async function getServerSideProps() {
    let dev = process.env.NODE_ENV !== 'production';
    let { DEV_URL, PROD_URL } = process.env;
    const educationRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/education`);
    const educationData = await educationRes.json();
    const experienceRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/experience`);
    const experienceData = await experienceRes.json();
    return {
        props: {
            educationData,
            experienceData,
        },
    }
}
