import Head from "next/head";
import Bio from "../../components/homeComps/bio";
import { loadEducation, loadExperience } from "../../lib/getLoadedData";

const About = ({educationData, experienceData}) => {
    return (
        <div>
            <Head>
                <title>About - Nahid Hossain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/boy.png" />
            </Head>
            <Bio 
                educations={educationData} 
                experiences={experienceData} 
            />
        </div>
    );
};

export default About;

export async function getServerSideProps() {
    try {
        const educationData = await loadEducation();
        const experienceData = await loadExperience();
        return {
            props: {
                educationData,
                experienceData,
            },
        }
    } catch (error) {
        console.log(error);
        return error
    }
}
