import Head from 'next/head';
import Image from 'next/image';
import Bio from '../components/homeComps/Bio';
import Header from '../components/homeComps/header';
import myImage from '/assets/herosec1.jpg';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Nahid Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/boy.png" />
      </Head>
    <div className='flex sm:flex-row flex-col-reverse justify-between mt-10'>
      <div className='sm:basis-3/4'>
        <Header />
        <Bio />
      </div>
      <div className='sm:mt-10 sm:basis-1/4'>
          <div className='sm:sticky sm:top-[116px]'>
            <Image className="rounded-full mx-auto" src={myImage} height={180} width={180} alt="Nahid" />
          </div>
      </div>
    </div>
    </div>
  )
}
