import Head from 'next/head';
import Image from 'next/image';
import Bio from '../components/homeComps/bio';
import Header from '../components/homeComps/header';
import Projects from '../components/homeComps/projects';
import myImage from '/assets/herosec1.jpg';


export default function Home({educationData, experienceData}) {
  return (
    <div>
      <Head>
        <title>Nahid Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/boy.png" />
      </Head>
    <div className='flex sm:flex-row flex-col-reverse justify-between mt-10'>
      <div className='sm:basis-3/4'>
        <Header />
        <Bio educations={educationData} experiences={experienceData} />
        <Projects />
      </div>
      <div className='sm:mt-10 sm:basis-1/4'>
          <div className='sm:sticky sm:top-[116px]'>
            <Image className="rounded-full mx-auto" src={myImage} height={180} width={180} alt="Nahid" />
          </div>
      </div>
    </div>
    </div>
  )
}

export async function getStaticProps() {
    const educationRes = await fetch('https://ndhossain.github.io/database/education.json');
    const educationData = await educationRes.json();
    const experienceRes = await fetch('https://ndhossain.github.io/database/experience.json');
    const experienceData = await experienceRes.json();
    return {
      props: {
        educationData,
        experienceData
      },
    }
}

