import Head from 'next/head';
import Image from 'next/image';
import Bio from '../components/homeComps/bio';
import Contact from '../components/homeComps/contact';
import Header from '../components/homeComps/header';
import Projects from '../components/homeComps/projects';
import myImage from '/assets/herosec1.jpg';


export default function Home({educationData, experienceData, projectsData}) {
  console.log(educationData);
  return (
    <div>
      <Head>
        <title>Nahid Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/boy.png" />
      </Head>
    <div className='flex sm:flex-row flex-col-reverse justify-between mt-10'>
      <div className='sm:basis-3/4'>
        <Header />
        <Bio 
          educations={educationData} 
          experiences={experienceData} 
        />
        <Projects projects={projectsData} />
        <Contact />
      </div>
      <div className='sm:mt-10 sm:basis-1/4'>
          <div className='sm:sticky sm:top-[116px]'>
            <Image className="rounded-full mx-auto" src={myImage} height={180} width={180} alt="Nahid" />
          </div>
      </div>
    </div>
    </div>
  )
}

export async function getStaticProps() {
    let dev = process.env.NODE_ENV !== 'production';
    let { DEV_URL, PROD_URL } = process.env;
    try {
      const educationRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/education`);
      const educationData = await educationRes.json();
      const experienceRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/experience`);
      const experienceData = await experienceRes.json();
      const projectsRes = await fetch(`${dev ? DEV_URL : PROD_URL}/api/projects`);
      const projectsData = await projectsRes.json();
      return {
        props: {
          educationData,
          experienceData,
          projectsData,
        },
      }
    } catch (error) {
      console.log(error)
    }
}
