import Head from "next/head";
import { AiFillInstagram, AiFillLinkedin } from 'react-icons/ai';
import { BsFileEarmarkPdf } from 'react-icons/bs';
import { FaGithubSquare } from 'react-icons/fa';
import { IoLogoFacebook } from 'react-icons/io';
import { SiGmail } from 'react-icons/si';


const Blogs = () => {
    return (
        <div style={{minHeight: 'calc(100vh - 245px)'}} className="my-10 flex justify-center items-center flex-col">
            <Head>
                <title>Blogs - Nahid Hossain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/boy.png" />
            </Head>
            <h1 className="text-3xl sm:text-6xl lg:text-9xl font-bold text-center">UNDER<br />CONSTRUCTION</h1>
            <div className='mt-10 flex gap-2'>
                <div className='hover:bg-slate-900/20 dark:hover:bg-white/20 rounded-full cursor-pointer p-2'>
                    <IoLogoFacebook size={22} />
                </div>
                <div className='hover:bg-slate-900/20 dark:hover:bg-white/20 rounded-full cursor-pointer p-2'>
                    <AiFillLinkedin size={22} />
                </div>
                <div className='hover:bg-slate-900/20 dark:hover:bg-white/20 rounded-full cursor-pointer p-2'>
                    <FaGithubSquare size={22} />
                </div>
                <div className='hover:bg-slate-900/20 dark:hover:bg-white/20 rounded-full cursor-pointer p-2'>
                    <AiFillInstagram size={22} />
                </div>
                <div className='hover:bg-slate-900/20 dark:hover:bg-white/20 rounded-full cursor-pointer p-2'>
                    <SiGmail size={22} />
                </div>
            </div>
        </div>
    );
};

export default Blogs;